// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Page = Collections['pages']['schema']['_output']
export declare const pages: Page[]
